---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ebs.aws.edenlab.io
  resources:
  - ebssnapshotprovisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ebs.aws.edenlab.io
  resources:
  - ebssnapshotprovisions/finalizers
  verbs:
  - update
- apiGroups:
  - ebs.aws.edenlab.io
  resources:
  - ebssnapshotprovisions/status
  verbs:
  - get
  - patch
  - update
