apiVersion: ebs.aws.edenlab.io/v1alpha1
kind: EBSSnapshotProvision
metadata:
  labels:
    app.kubernetes.io/name: ebssnapshotprovision
    app.kubernetes.io/instance: ebssnapshotprovision-sample
    app.kubernetes.io/part-of: ebs-snapshot-provision
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ebs-snapshot-provision
  name: ebssnapshotprovision-sample
spec:
  clusterName: deps-develop
  region: us-east-1
  frequency: 1m
  volumeSnapshotClassName: ebs-csi-snapshot-class
