//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 Edenlab
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotProvision) DeepCopyInto(out *EBSSnapshotProvision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotProvision.
func (in *EBSSnapshotProvision) DeepCopy() *EBSSnapshotProvision {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotProvision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EBSSnapshotProvision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotProvisionList) DeepCopyInto(out *EBSSnapshotProvisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EBSSnapshotProvision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotProvisionList.
func (in *EBSSnapshotProvisionList) DeepCopy() *EBSSnapshotProvisionList {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotProvisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EBSSnapshotProvisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotProvisionSpec) DeepCopyInto(out *EBSSnapshotProvisionSpec) {
	*out = *in
	if in.Frequency != nil {
		in, out := &in.Frequency, &out.Frequency
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotProvisionSpec.
func (in *EBSSnapshotProvisionSpec) DeepCopy() *EBSSnapshotProvisionSpec {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotProvisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotProvisionStatus) DeepCopyInto(out *EBSSnapshotProvisionStatus) {
	*out = *in
	if in.CreatedTime != nil {
		in, out := &in.CreatedTime, &out.CreatedTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotProvisionStatus.
func (in *EBSSnapshotProvisionStatus) DeepCopy() *EBSSnapshotProvisionStatus {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotProvisionStatus)
	in.DeepCopyInto(out)
	return out
}
