//go:build !ignore_autogenerated

/*
Copyright 2026 Edenlab.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotProvision) DeepCopyInto(out *EBSSnapshotProvision) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotProvision.
func (in *EBSSnapshotProvision) DeepCopy() *EBSSnapshotProvision {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotProvision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EBSSnapshotProvision) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotProvisionList) DeepCopyInto(out *EBSSnapshotProvisionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EBSSnapshotProvision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotProvisionList.
func (in *EBSSnapshotProvisionList) DeepCopy() *EBSSnapshotProvisionList {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotProvisionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EBSSnapshotProvisionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotProvisionSpec) DeepCopyInto(out *EBSSnapshotProvisionSpec) {
	*out = *in
	if in.Frequency != nil {
		in, out := &in.Frequency, &out.Frequency
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotProvisionSpec.
func (in *EBSSnapshotProvisionSpec) DeepCopy() *EBSSnapshotProvisionSpec {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotProvisionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotProvisionStatus) DeepCopyInto(out *EBSSnapshotProvisionStatus) {
	*out = *in
	if in.SnapshotsCreatedByNamespace != nil {
		in, out := &in.SnapshotsCreatedByNamespace, &out.SnapshotsCreatedByNamespace
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotProvisionStatus.
func (in *EBSSnapshotProvisionStatus) DeepCopy() *EBSSnapshotProvisionStatus {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotProvisionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRetention) DeepCopyInto(out *EBSSnapshotRetention) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRetention.
func (in *EBSSnapshotRetention) DeepCopy() *EBSSnapshotRetention {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRotation) DeepCopyInto(out *EBSSnapshotRotation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRotation.
func (in *EBSSnapshotRotation) DeepCopy() *EBSSnapshotRotation {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRotation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EBSSnapshotRotation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRotationList) DeepCopyInto(out *EBSSnapshotRotationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EBSSnapshotRotation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRotationList.
func (in *EBSSnapshotRotationList) DeepCopy() *EBSSnapshotRotationList {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRotationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EBSSnapshotRotationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRotationSpec) DeepCopyInto(out *EBSSnapshotRotationSpec) {
	*out = *in
	if in.Frequency != nil {
		in, out := &in.Frequency, &out.Frequency
		*out = new(v1.Duration)
		**out = **in
	}
	if in.SnapshotRotations != nil {
		in, out := &in.SnapshotRotations, &out.SnapshotRotations
		*out = make(map[string]SnapshotRotationTarget, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRotationSpec.
func (in *EBSSnapshotRotationSpec) DeepCopy() *EBSSnapshotRotationSpec {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRotationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EBSSnapshotRotationStatus) DeepCopyInto(out *EBSSnapshotRotationStatus) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make(map[string]SnapshotRotationTargetStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EBSSnapshotRotationStatus.
func (in *EBSSnapshotRotationStatus) DeepCopy() *EBSSnapshotRotationStatus {
	if in == nil {
		return nil
	}
	out := new(EBSSnapshotRotationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRotationTarget) DeepCopyInto(out *SnapshotRotationTarget) {
	*out = *in
	if in.PVCSelector != nil {
		in, out := &in.PVCSelector, &out.PVCSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Retention = in.Retention
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRotationTarget.
func (in *SnapshotRotationTarget) DeepCopy() *SnapshotRotationTarget {
	if in == nil {
		return nil
	}
	out := new(SnapshotRotationTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRotationTargetStatus) DeepCopyInto(out *SnapshotRotationTargetStatus) {
	*out = *in
	if in.SnapshotsCreated != nil {
		in, out := &in.SnapshotsCreated, &out.SnapshotsCreated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SnapshotsDeleted != nil {
		in, out := &in.SnapshotsDeleted, &out.SnapshotsDeleted
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRotationTargetStatus.
func (in *SnapshotRotationTargetStatus) DeepCopy() *SnapshotRotationTargetStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotRotationTargetStatus)
	in.DeepCopyInto(out)
	return out
}
